@host=http://localhost:8080/api/v1
@token={{logintwofactor.response.body.data.token}}

### GET SOMETINH
# @name login
# @prompt email
# @prompt password
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### GET Two factor
# @name logintwofactor
# @prompt email
# @prompt password
POST {{host}}/auth/two-factor/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Get Two factor
# @name verifytwofactor
# @prompt email
# @prompt access
POST {{host}}/auth/two-factor/token
Content-Type: application/json

{
  "email": "{{email}}",
  "access": "{{access}}"
}

### Create Account
# @prompt name
# @prompt lastname
# @prompt email
# @prompt password
POST {{host}}/auth/register
Content-Type: application/json

{
  "name": "{{name}}",
  "lastname": "{{lastname}}",
  "email": "{{email}}",
  "password": "{{password}}"
}

### Request Change Password
POST {{host}}/auth/request-password
Content-Type: application/json

{
  "email": "admin@gmail.com"
}

### Validate Token
POST {{host}}/auth/validate-request
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "code": "545970"
}

### Update Password
POST {{host}}/auth/update-password
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "code": "545970",
  "password": "4321"
}