@host=http://localhost/uniandes-web/api/v1
@token={{login.response.body.data.token}}

### GET SOMETINH
# @name login
# @prompt email
# @prompt password
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Create Account
POST {{host}}/auth/register
Content-Type: application/json

{
  "name": "secret",
  "lastname": "hidden",
  "email": "hidden@gmail.com",
  "password": "123456789"
}

### Request Change Password
POST {{host}}/auth/request-password
Content-Type: application/json

{
  "email": "grober@gmail.com"
}

### Validate Token
POST {{host}}/auth/validate-request
Content-Type: application/json

{
  "email": "grober@gmail.com",
  "code": "235216"
}

### Update Password
POST {{host}}/auth/update-password
Content-Type: application/json

{
  "email": "grober@gmail.com",
  "code": "235216",
  "password": "grober"
}