@host=http://localhost/uniandes-web/api/v1
@token={{login.response.body.data.token}}

### LOGIN
# @name login
# @prompt email
# @prompt password
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Get All Fines
GET {{host}}/fine
Authorization: Bearer {{token}}

### Get All Fines
GET {{host}}/fine/1
Authorization: Bearer {{token}}

### Create A Fine
POST {{host}}/fine
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="json"

{
  "id_ticket": 1,
  "amount": 11,
  "description": "What the fuck!"
}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="flcl.png"
Content-Type: image/png

< /home/poggers/img/anime.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Get Image
GET http://localhost/uniandes-web/storage/fine/1_12.png

### Get Image
GET http://localhost/uniandes-web/api/v1/storage/fine/1_12.png

### Pay one
POST {{host}}/fine/pay/1
Authorization: Bearer {{token}}

### Cancel one
POST {{host}}/fine/cancel/11
Authorization: Bearer {{token}}
