@host=http://localhost/uniandes-web/api/v1

### Create A Fine
POST {{host}}/fine
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="json"

{
  "id_ticket": 1,
  "amount": 123,
  "state": 123123,
  "description": "Hello World"
}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="urabe.jpg"
Content-Type: image/jpeg

< /home/poggers/img/urabe.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Get Image
GET http://localhost/uniandes-web/storage/fine/1_2.jpg
