@host=http://localhost/uniandes-web/api/v1
@token={{login.response.body.data.token}}

### GET SOMETINH
# @name login
# @prompt email
# @prompt password
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Profile
POST {{host}}/profile/update
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "grober",
  "lastname": "gonzales"
}

### Update Password
# @prompt password
# @prompt new-password
POST {{host}}/profile/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "password": "{{password}}",
  "new-password": "{{new-password}}"
}

### Get Tickets
GET {{host}}/profile/tickets
Authorization: Bearer {{token}}

### Get Fines
GET {{host}}/profile/fines
Authorization: Bearer {{token}}
