@host=http://localhost/uniandes-web/api/v1
@token={{login.response.body.data.token}}

### LOGIN
# @name login
# @prompt email
# @prompt password
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}
### Get All
GET {{host}}/ticket
Authorization: Bearer {{token}}

### Get From user
GET {{host}}/profile/tickets
Authorization: Bearer {{token}}

### GET al vehicles
GET {{host}}/vehicle
Authorization: Bearer {{token}}

### Get One
GET {{host}}/ticket/1
Authorization: Bearer {{token}}

### Create One
POST {{host}}/ticket
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id_space": 4,
  "id_vehicle": 1
}

### Completed
POST {{host}}/ticket/completed/2
Authorization: Bearer {{token}}

### Completed
POST {{host}}/ticket/cancel/2
Authorization: Bearer {{token}}
