@host=http://localhost/uniandes-web/api/v1
@token={{login.response.body.data.token}}

### LOGIN
# @name login
# @prompt email
# @prompt password
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Get all users
GET {{host}}/user
Authorization: Bearer {{token}}

### Get One User
GET {{host}}/user/1
Authorization: Bearer {{token}}

### Create USer
POST {{host}}/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "cliente",
  "lastname": "lastname",
  "email": "cliente@gmail.com",
  "password": "1234",
  "state": 1,
  "role": "cliente"
}

### Update USer
PUT {{host}}/user/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "grober",
  "lastname": "gonzales",
  "email": "grober@gmail.com",
  "password": "123456789",
  "role": "admin",
  "state": 1
}

### Delete User
DELETE {{host}}/user/1
Authorization: Bearer {{token}}

### Enagle User
POST {{host}}/user/1/enable
Authorization: Bearer {{token}}