@host=http://localhost:8080/api/v1
@token={{login.response.body.data.token}}

### LOGIN
# @name login
# @prompt email
# @prompt password
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Vechile
GET {{host}}/vehicle
Authorization: Bearer {{token}}

### Get One
GET {{host}}/vehicle/1
Authorization: Bearer {{token}}

### Create One
POST {{host}}/vehicle
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id_user": null,
  "plate": "ABCD",
  "brand": "xd",
  "model": "XDXD",
  "year": 23,
  "taxable_base": 123
}

### Update One
PUT {{host}}/vehicle/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id_user": null,
  "plate": "ASD3",
  "brand": "xdxd",
  "model": "XDXD2",
  "year": 1023,
  "taxable_base": 1
}

### Delete One
DELETE {{host}}/vehicle/2
Authorization: Bearer {{token}}

### GET Vehicules without user
GET {{host}}/vehicle/without-user
Authorization: Bearer {{token}}

### GET Vehicules by user
GET {{host}}/vehicle/user/1
Authorization: Bearer {{token}}

### Update vehicle user
PUT {{host}}/vehicle/update
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id_vehicle": 3,
  "id_user": 2
}